# Generated by Django 4.0.3 on 2022-03-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
