# Generated by Django 4.0.3 on 2022-03-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
